### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by sbryfcz** [renketsu0/oculus_data_vis#14]
Hey Guys,
Any thought I why I cant compile this code. I get this error:

Assets/unity-ui-extensions/Scripts/CurvedText.cs(8,18): error CS0534: `UnityEngine.UI.Extensions.CurvedText' does not implement inherited abstract member`UnityEngine.UI.BaseMeshEffect.ModifyMesh(UnityEngine.UI.VertexHelper)'

I'd love to run this locally.

**Comment by jmarsh411** [comment]
Were you able to get this running with Unity 5.2.1? If so I would like to close the issue.
